export const MACHINERY = [
  "Tractor",
  "Rotavator",
  "Disc Plough",
  "Harrow",
  "Laser Land Leveler",
  "Seed Drill",
  "Zero-Till Drill",
  "Rice Transplanter",
  "Potato Planter",
  "Cono Weeder",
  "Power Weeder",
  "Tractor-Mounted Cultivator",
  "Knapsack Sprayer",
  "Power Sprayer",
  "Tractor-Mounted Boom Sprayer",
  "Combine Harvester",
  "Pedal Thresher",
  "Multi-Crop Thresher",
  "Happy Seeder",
  "Straw Baler",
  "Straw Chopper",
  "Manual Chaff Cutter",
  "Electric Chaff Cutter",
  "Portable Crop Residue Chopper",
  "Chaff Cutter",
  "Forage Harvester",
  "Mower-Conditioner",
  "Airblast Sprayer",
  "Pruning Saw",
  "Fruit Harvester",
  "Orchard Tractor"
];

export default MACHINERY;

