export const MACHINERY = [
  "Tractor (with various implements)",
  "Rotavator (for seedbed preparation)",
  "Disc Plough (primary tillage)",
  "Harrow (soil leveling)",
  "Laser Land Leveler (precision leveling in Punjab/Haryana)",
  "Seed Drill (including seed-cum-fertilizer models)",
  "Zero-Till Drill (for wheat in conservation agriculture)",
  "Rice Transplanter (mechanical, common in South India)",
  "Potato Planter (manual/semi-automatic in UP/WB)",
  "Cono Weeder (manual, paddy fields)",
  "Power Weeder (2-stroke engine, Tamil Nadu/Kerala)",
  "Tractor-Mounted Cultivator (inter-row weeding)",
  "Knapsack Sprayer (manual, ubiquitous for small farms)",
  "Power Sprayer (5HP engine-operated)",
  "Tractor-Mounted Boom Sprayer (large fields)",
  "Combine Harvester (for wheat/paddy, e.g., 'Class' or 'Kartar')",
  "Pedal Thresher (small farms, Eastern India)",
  "Multi-Crop Thresher (diesel-operated)",
  "Happy Seeder (direct sowing through residue)",
  "Straw Baler (round bales for industrial use)",
  "Straw Chopper (attachable to combines)",
  "Manual Chaff Cutter (₹3,000–5,000, rural households)",
  "Electric Chaff Cutter (1–3HP, dairy farms)",
  "Portable Crop Residue Chopper (for paddy straw)",
  "Chaff Cutter (diesel/electric, 500 kg/hr capacity)",
  "Forage Harvester (tractor-PTO operated)",
  "Mower-Conditioner (for haymaking)",
  "Airblast Sprayer (mango/citrus orchards)",
  "Pruning Saw (manual/pneumatic)",
  "Fruit Harvester (mango ladders with catch frames)",
  "Orchard Tractor (narrow 45HP models, Maharashtra/Nashik)"
];

export default MACHINERY;
